formatter: "markdown"

version: ""

header-from: main.tf
footer-from: ""

recursive:
  enabled: false
  path: modules
  include-main: true

sections:
  hide: []
  show: []

content: |-

    {{ .Header }}

    ## Examples

    ### AlmaLinux 8

    ```hcl
    {{ include "examples/almalinux8/main.tf" }}
    ```

    ### Debian 11

    ```hcl
    {{ include "examples/debian11/main.tf" }}
    ```

    ### CBL Mariner

    ```hcl
    {{ include "examples/cbl-mariner/main.tf" }}
    ```

    ### OpenSuse

    ```hcl
    {{ include "examples/opensuse/main.tf" }}
    ```


    ### Example Ubuntu 18.04

    ```hcl
    {{ include "examples/ubuntu1804/main.tf" }}
    ```

    ### Example Ubuntu 20.04

    ```hcl
    {{ include "examples/ubuntu2004/main.tf" }}
    ```
    ### Example Ubuntu 22.04

    ```hcl
    {{ include "examples/ubuntu2204/main.tf" }}
    ```

    {{ .Inputs }}
    {{ .Modules }}
    {{ .Outputs }}
    {{ .Providers }}
    {{ .Resources }}
    {{ .Requirements }}
    {{ .Footer }}

output:
  file: ""
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
